version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Installing NPM dependencies...
            - npm install
    pre_build:
        commands:
    build:
        commands:
            - echo Building project...
            - npm run build
discard-paths: no
base-directory: build
