version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      nodejs: 16
  pre_build:
    commands:
      - echo Logging into AWS...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo SECRET = $SECRET
      - export TEST1=$SECRET
      - echo Foo = $Foo
      - export TEST2=$Foo
  build:
    commands:
      - echo Building Docker...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker to AWS ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
