CREATE TABLE IF NOT EXISTS Users (
	 id			VARCHAR(32)		NOT NULL	UNIQUE
	,first_name	VARCHAR(50)		NOT NULL
	,last_name	VARCHAR(50)		NOT NULL
	,cpf		VARCHAR(11)		NOT NULL	UNIQUE
	,rg			VARCHAR(11)		NOT NULL	UNIQUE
	,phone		VARCHAR(11)		NOT NULL	UNIQUE
	,email		VARCHAR(50)		NOT NULL	UNIQUE
	,password	VARCHAR			NOT NULL
	,birthday	DATE			NOT NULL
	,address	VARCHAR(100)	NOT NULL
	,created_at	TIMESTAMP		NOT NULL
	,updated_at	TIMESTAMP		NOT NULL
	,deleted_at	TIMESTAMP		
)