CREATE TABLE IF NOT EXISTS Users (
	 id			VARCHAR(50)		NOT NULL	UNIQUE
	,firstName	VARCHAR(50)		NOT NULL
	,lastName	VARCHAR(50)		NOT NULL
	,cpf		VARCHAR(11)		NOT NULL	UNIQUE
	,rg			VARCHAR(11)		NOT NULL	UNIQUE
	,phone		VARCHAR(11)		NOT NULL	UNIQUE
	,email		VARCHAR(50)		NOT NULL	UNIQUE
	,password	VARCHAR			NOT NULL
	,birthday	DATE			NOT NULL
	,address	VARCHAR(100)	NOT NULL
	,createdAt	TIMESTAMP		NOT NULL
	,updatedAt	TIMESTAMP		NOT NULL
	,deletedAt	TIMESTAMP		
)